# Generated by Django 5.0 on 2023-12-15 20:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, upload_to='restaurant/food_photos'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.9899999999999999911182158029987476766109466552734375'), max_digits=5),
        ),
    ]
