# Generated by Django 5.0 on 2023-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
