# Generated by Django 5.0 on 2024-01-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menu_id_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menu'),
        ),
    ]
