# Generated by Django 5.0 on 2023-12-16 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('PD', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('DV', 'Delivered'), ('CL', 'Cancelled')], default='OP', max_length=2),
        ),
    ]
