# Generated by Django 5.0 on 2023-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_client_alter_order_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='peding_cancelation',
            field=models.BooleanField(default=False),
        ),
    ]
