# Generated by Django 5.0 on 2023-12-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_peding_cancelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='peding_cancelation',
            new_name='pending_cancelation',
        ),
    ]
