# Generated by Django 5.0 on 2023-12-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_peding_cancelation_order_pending_cancelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pending_cancelation',
            new_name='pending_cancellation',
        ),
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
