# Generated by Django 5.0 on 2024-01-23 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_pending_cancelation_order_pending_cancellation_and_more'),
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='order',
            name='tab',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
    ]
