# Generated by Django 5.0 on 2024-01-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_client_remove_order_qr_code_order_tab'),
        ('restaurant', '0013_alter_food_menu'),
        ('tab', '0002_alter_tab_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tab',
            field=models.ForeignKey(default='39fcaabf-8674-48fc-9618-d48db2556a97', editable=False, on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
