# Generated by Django 5.0 on 2024-01-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_tab'),
        ('tab', '0006_alter_historictab_order_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tab',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tab.tab'),
        ),
    ]
