# Generated by Django 5.0.1 on 2024-01-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_tab_order_tab_id_order_tab_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
