# Generated by Django 5.0 on 2024-01-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_alter_tab_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='historic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tab',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes'),
        ),
    ]
