# Generated by Django 5.0 on 2024-01-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_tab'),
        ('restaurant', '0013_alter_food_menu'),
        ('tab', '0008_alter_historictab_order_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='restaurant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='historictab',
            name='order_set',
            field=models.ManyToManyField(editable=False, to='order.order'),
        ),
    ]
