# Generated by Django 5.0.1 on 2024-01-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_tab_restaurant_alter_historictab_order_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historictab',
            name='order_set',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='historictab',
            name='client',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
