# Generated by Django 5.0.1 on 2024-01-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_food_menu'),
        ('tab', '0011_alter_historictab_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='historictab',
            name='restaurant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant'),
        ),
    ]
